name: test_ramedia
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.3.2
  geolocator: ^10.1.0
  network_info_plus: ^4.1.0
  connectivity_plus: ^5.0.1
  auto_route: ^7.8.3
  get_it: ^7.6.4
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_inappwebview: 6.0.0-beta.25
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  flame: ^1.10.0
  flame_audio: ^1.3.0
  flame_forge2d: ^0.16.0
  geocoding: ^2.0.0









  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/audio/
    - assets/images/
    - assets/audio/sfx/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
